# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20170128_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='jaime',
            new_name='like',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='categorie',
            new_name='section',
        ),
    ]
