# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 17:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20170129_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dateactive',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 29, 17, 9, 7, 258020, tzinfo=utc), verbose_name="Date d'activité"),
        ),
    ]
